services:
  db:
    container_name: postgres-magalu
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_agendamento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db_agendamento" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: agendamento
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_agendamento
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
