services:
  db:
    container_name: postgres-magalu
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_agendamento
    ports:
      - 5432:5432
